name: Build and deploy flutter apps.
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: "Build and deploy flutter web app."
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test_counter_app

    steps:
      - name: checkout files
        uses: actions/checkout@v3

      - name: enable flutter web
        run: flutter config --enable-web

      - name: set up flutter 
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: pull dependencies
        run: flutter pub get

      - name: run tests
        run: flutter test
        
      - name: build web app
        run: flutter build web --web-renderer=canvaskit --base-href='/flutter_staging/'

      - name: deploy to gh pages
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: test_counter_app/build/web
