name: gh-pages 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Build and deploy flutter app to GH pages
      working-directory: ./test_counter_app
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
