name: Build and deploy flutter apps.
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: "Build and deploy flutter web app."
    runs-on: ubuntu-latest

    steps:
      - name: checkout files
        uses: actions/checkout@v3

      - name: set up flutter 
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: enable flutter web
        working-directory: definitely_not_breakout
        run: flutter config --enable-web

      - name: pull dependencies
        working-directory: definitely_not_breakout
        run: flutter pub get
        
      - name: build web app
        working-directory: definitely_not_breakout
        run: flutter build web --web-renderer canvaskit --base-href /flutter_staging/ --release

      - name: deploy to gh pages
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: definitely_not_breakout/build/web
